/* eslint-disable @next/next/no-img-element */
import { Style } from './styles'

import Footer from './Footer'
import Header from './Header'

import Section from 'components/organisms/Section'

import { TNextPageWithLayout } from 'typescript/next.types'

import Head from 'next/head'

const Home: TNextPageWithLayout = () => (
  <>
    <Head>
      <title>Home</title>

      <meta name='description' content='Generated by create next app' />

      <link rel='icon' href='/favicon.ico' />
    </Head>

    <Header />

    <Style>
      <Section
        image='./mercurial.png'
        buttonText='Ver Mercurial'
        title='A VELOCIDADE ESTÁ NO AIR'
        mobileImage='./mercurial-mobile.png'
        content='Descubra um novo tipo de velocidade. Apresentando a Air Zoom Mercurial.'
      />

      <Section
        image='./mercurial.png'
        buttonText='Ver Mercurial'
        title='A VELOCIDADE ESTÁ NO AIR'
        mobileImage='./mercurial-mobile.png'
        content='Descubra um novo tipo de velocidade. Apresentando a Air Zoom Mercurial.'
      />
    </Style>

    <Footer />
  </>
)

export default Home
