import { Style } from './styles'

import { TNextPageWithLayout } from 'typescript/next.types'

import Head from 'next/head'

const Home: TNextPageWithLayout = () => (
  <>
    <Head>
      <title>Home</title>

      <meta name='description' content='Generated by create next app' />

      <link rel='icon' href='/favicon.ico' />
    </Head>

    <Style className='text-3xl font-bold underline mx-20'>
      <button className='btn'>Hello Next</button>
    </Style>
  </>
)

export default Home
