import { Style } from './styles'

import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => (
  <>
    <Head>
      <title>Home</title>

      <meta name='description' content='Generated by create next app' />

      <link rel='icon' href='/favicon.ico' />
    </Head>

    <Style className='text-3xl font-bold underline mx-20 bg-red-500'>
      Hello Next
    </Style>
  </>
)

export default Home
